version: '3'
volumes:
    node-modules:
services:
    next:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - node-modules:/app/node_modules
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: 'npm run start'
        ports:
            - '3000:3000'
