version: '3'
services:
    app:
        build:
            context: .
        ports:
            - '3000:3000'
            - '6006:6006'
        volumes:
            - '.:/app'
        environment:
            NODE_ENV: development
