version: '3'
volumes:
    node-modules:
services:
    next:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - node-modules:/app/node_modules
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        command: sh -c "npm run dev"
        ports:
            - '3000:3000'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
